# -*- coding: utf-8 -*-
"""code 6.ipy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VD88z02KLru6scjqZuKmqWoCYemPPrHB
"""

count=1
while count<=5:
  print("hello")
  count+=1

#print number from 1 to 5
n=1
while n<=5:
  print(n)
  n+=1

#print number from 5 to 1
n=5
while n>=1:
  print(n)
  n-=1

#print number from 1 to 100
n=1
while n<=100:
  print(n)
  n+=1

#print number from 100 to 1
n=100
while n>=1:
  print(n)
  n-=1

#write the table of 4
i=1
while i<=10:
  print(4*i)
  i+=1

list=[1,4,9,16,25,36,49,64,81,100]
idx=0
while idx<len(list):
  print(list[idx])
  idx+=1

tuple=(1,4,9,16,25,36,49,64,81,100)

k=64


i=0
while i<len(tuple):
  if(tuple[i]==k):
    print("found at index",i)
    i+=1

